# Generated by Django 4.1.7 on 2023-03-12 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('volume', models.IntegerField()),
                ('owner', models.ForeignKey(db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CupMaterials',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cup', models.ForeignKey(db_column='cup_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cup')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.PROTECT, to='accounting.material')),
            ],
            options={
                'db_table': 'accounting_cup_materials',
            },
        ),
        migrations.AddField(
            model_name='cup',
            name='shelf',
            field=models.ForeignKey(db_column='shelf_id', on_delete=django.db.models.deletion.CASCADE, to='accounting.shelf'),
        ),
    ]
